### ISSUE TITLE
Changing the database in the datasource configuration takes no effect in the queries

### ISSUE THREAD

**Issue by andresmgot** [grafana/athena-datasource#105]
**What happened**:

If the database is changed in the datasource configuration page, queries will still use the previous database (until grafana server is restarted).

**What you expected to happen**:

The new database to be used.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an Athena datasource.
2. Select a database. Save the datasource.
3. Change the database.
4. Create a new panel. The database selector will show `default (new database)` but if you try to list tables or write a query, it will use the first database.

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version: 1.0.1
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by andresmgot** [comment]
I will fix as part of the development in the new [SDK refactoring](https://github.com/grafana/athena-datasource/tree/awsSDK) (it's not worth it to fix it in main since I will change it later).

The problem is that this [`GetDB` function](https://github.com/grafana/athena-datasource/blob/awsSDK/pkg/athena/datasource.go#L54) is returning the cached connection ([here](https://github.com/grafana/grafana-aws-sdk/blob/main/pkg/sql/datasource/datasource.go#L132)) but we need a new one.

**Comment by sarahzinger** [comment]
I'm seeing a new bug that I think might be the same issue:
- I create a new athena datasource with access/secret key but don't put in an ARN (even though that access key requires it to work properly). 
- I try to select a database and see an error that I don't have permission (this is as expected as I'm missing the arn). 
- I click save and test and I see an expected error that I'm missing the default database
- I then try to add the arn
- I then try to select a default database and see an unexpected error that I do not have permission as it seems to be using the old connection without the arn.
