### ISSUE TITLE
Grafana shows 0 when doing a math expression combining two AWS Athena queries

### ISSUE THREAD

**Issue by jfagoagas** [grafana/athena-datasource#106]
**What happened**:
I'm trying to create a new panel combining two queries using a mathematical expression and when I do it Grafana shows 0 results in every query.
- Query A: `select count(*) from $__table where fieldA = '$varA' and fieldB = '$varB' and fieldC = 'valueC';`
- Query B: `select count(*) from $__table where fieldA = '$varA' and fieldB = '$varB';`
- Expression C: `($A * 100) / $B`
![Screenshot 2021-12-27 at 10 21 22](https://user-images.githubusercontent.com/16007882/147456773-5b866d15-6022-4542-b0b4-b53b9e3ae854.png)

Both query results A and B has values different than 0 like you can see in the following image:
![Screenshot 2021-12-27 at 10 29 21](https://user-images.githubusercontent.com/16007882/147457581-28950150-c745-4009-8730-a030882490fa.png)

I'm using "stat" visualization.

**What you expected to happen**:
A new panel with the result of the mathematical expression.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new empty panel using Athena's datasource plugin.
2. Create a new query A with a `count` SQL expression.
3. Create a new query B with a `count` SQL expression.
4. Hide both previous queries.
5. Create a new math expression combining this two queries `($A * 100) / $B`

**Screenshots**
I have uploaded above.

**Anything else we need to know?**:
If I check container's log I can see the following:

```
t=2021-12-27T09:35:27+0000 lvl=eror msg="expression request error" logger=context userId=1 orgId=1 uname=user error="failed to query data: Failed to query data: rpc error: code = Canceled desc = context canceled" remote_addr=172.17.0.1
t=2021-12-27T09:35:27+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=user method=POST path=/api/ds/query status=500 remote_addr=172.17.0.1 time_ms=1289 size=38 referer="http://127.0.0.1:3000/d/S8aCNR0nz/new-dashboard-copy?orgId=1&var-A=A&var-date=2021-12-27&editPanel=14"
t=2021-12-27T09:35:30+0000 lvl=eror msg="expression request error" logger=context userId=1 orgId=1 uname=user error="failed to query data: Failed to query data: rpc error: code = Canceled desc = context canceled" remote_addr=172.17.0.1
```
**Environment**:
- Grafana version: v8.2.3 (fb85ed6912)
- Plugin version: 1.0.1
- OS Grafana is installed on: Docker, fresh new installation
- User OS & Browser: macOS 12.0.1 & Chrome 96.0.4664.110
- Others:

**Comment by jfagoagas** [comment]
I have been trying to figure out more about this issue and it is somewhat complicated to reproduce.

With a simple query it works perfect:
- First two queries:
![Screenshot 2021-12-27 at 15 16 47](https://user-images.githubusercontent.com/16007882/147480081-e27a581d-db23-421c-ad3b-1b05ff74b743.png)
- Math expression:
![Screenshot 2021-12-27 at 15 16 59](https://user-images.githubusercontent.com/16007882/147480084-ac85b2df-4223-4d01-8cfb-fd4234ea4718.png)

**Comment by jfagoagas** [comment]
@sp-aliciaalcalde

**Comment by sarahzinger** [comment]
I can recreate this on my end with the following steps:
- I create a template variable with this query (although I imagine any would work) `select distinct bill_billing_entity from o11y_costs`
- then I created a panel using that query `select count(*) from $__table where bill_billing_entity = '$billingentity'`
- the query loads fine with an amount over 30,000
- then I add a math expression: `$A + 1` and I get back the results, 0 for a and 1 for b. If I delete the expression I get back a value over 30,000 for A. 

If I remove the template variables, everything works as expected. 

I'll take a look this week and see if I can figure out what's going on.

**Comment by jfagoagas** [comment]
Thank you very much @sarahzinger, this is the behaviour that I'm experiencing.

Please, let me know if I can do anything by my side.

**Comment by sarahzinger** [comment]
@jfagoagas I took another look and it seems that this is an issue with a beta feature in core grafana, and not the athena plugin. Good news is that it's already being investigated and worked on 🎉 https://github.com/grafana/grafana/issues/37636

Going to close this in favor of 37636.

**Comment by jfagoagas** [comment]
Thank you @sarahzinger, I'll look at this issue.
