### ISSUE TITLE
Query executed on Athena every time a panel is viewed, instead of caching

### ISSUE THREAD

**Issue by joshvazquez** [grafana/athena-datasource#115]
**What happened**:
Every time I view my panel, the graph is blank and a query to Athena is made. This happens whether the dashboard time range is relative or fixed (e.g. choosing a fixed range and refreshing the page to request the same range again). The query is static and contains no macros, so it is identical every time it is run.

If the time range is changed after initial load (e.g. dragging a box to zoom in), a new query is made instead of redrawing the existing graph.

**What you expected to happen**:
Opening a dashboard repeatedly avoids repeated calls to Athena for the same query, caching results instead. Zooming in does not result in a new query. Zooming out (up to the extents of the most recent query results) does not result in a new query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel.
2. Query:
```
select sum(duration_seconds)/3600 as duration_hours, date_trunc('day', date_parse(start_time,'%Y-%m-%d %H:%i:%s.%f')) as time from my_table
where mycol = 'MyValue'
group by date_trunc('day', date_parse(start_time,'%Y-%m-%d %H:%i:%s.%f'))
order by time
```
3. Save the panel to a dashboard.
4. Navigate to the dashboard.
5. In Athena, observe that a query was made.
6. Navigate away from the dashboard and navigate to it again.
7. In Athena, observe that another identical query was made.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Plugin version: 1.0.0
- OS Grafana is installed on: AMG
- User OS & Browser: macOS 10.15.7, Firefox 91.4.0esr

**Comment by joshvazquez** [comment]
There is no Cache tab in the data source settings and no "Cache timeout" option in query options for this data source.

**Comment by andresmgot** [comment]
Thanks for the issue, I see that you found the discussion at https://github.com/grafana/athena-datasource/discussions/86 so let's keep the conversation there for readability. I'll comment here in line anyway this time:

> **What you expected to happen**:
> Opening a dashboard repeatedly avoids repeated calls to Athena for the same query, caching results instead.

Yes, that's the goal of the Grafana query caching (more details in the discussion).

> Zooming in does not result in a new query. Zooming out (up to the extents of the most recent query results) does not result in a new query.

This will only works if the query remains the same (with the caching system), which is the case of the example you posted I. If the query depends on the time range (e.g. using the `timeFilter` macro), the query will be different so a new query will be issued. 

> There is no Cache tab in the data source settings and no "Cache timeout" option in query options for this data source.

It's not clear to me if query caching is already or will be available in AMG, I have asked this to the team to get more info, I will reply once I get this information in the discussion. 

> 2\. Query:

Unrelated to this issue but I'd recommend you to use the macro `$__dateFilter` to filter by date, so you reduce the data queried :)
