### ISSUE TITLE
 InvalidRequestException while creating variable in Athena/Grafana

### ISSUE THREAD

**Issue by avikkumar1983** [grafana/athena-datasource#134]
While trying to create a new variable based on a column name in Athena I am facing this issue. Not sure what needs to be done .

![image](https://user-images.githubusercontent.com/61217148/158049200-252bdd04-28c6-49e4-8020-55baf372d33d.png)

**Comment by andresmgot** [comment]
Hi @avikkumar1983, that's an Athena syntax error, you need to quote the database name since it contains `-`: `SELECT ... from "atlas-cw-metric".tablename`.

Please reopen if you still think there is an issue with the plugin.

**Comment by avikkumar1983** [comment]
Thanks I corrected the error by-
 mentioning proper dbname along with table name
also my glue table has partition projection based on datehour column.
```
SELECT
distinct metric_name
FROM dbname.tablename
WHERE
datehour BETWEEN TIMESTAMP '2022-03-13 17:43:23' AND TIMESTAMP '2022-03-13 19:23:23'
```
