### ISSUE TITLE
Error message not forwarded when listing resources in ConfigEditor

### ISSUE THREAD

**Issue by andresmgot** [grafana/athena-datasource#141]
### Discussed in https://github.com/grafana/athena-datasource/discussions/140

<div type='discussions-op-text'>

<sup>Originally posted by **yumam** March 27, 2022</sup>
![image](https://user-images.githubusercontent.com/56136651/160302255-8f19371f-7935-43af-85b8-81489e4e179e.png)

Hello, I'm having an issue setting up AWS Athena as a data source in Grafana. I've set up my user permission to have AmazonAthenaFullAccess and still it's not retrieving anything for 'Data source'. 
I'm on Windows 10 using Grafana Cloud through Chrome.

Anything I'm missing here? Thanks.</div>

**Comment by andresmgot** [comment]
Thanks for the report @yumam

This is probably an authentication issue. Can you check the network tab of your browser? There should be a call to and endpoint "catalogs" to return the error.

I am converting this to an issue since the error should be propagated to the UI anyway.

**Comment by thorbjornvynne** [comment]
Hi @andresmgot  I'm seeing the same thing. But if I use the explore option I can get those fields updated. Let me know what I should provide.

I ended up using a hardcoded datasource config to solve this.

**Comment by Timyang860629** [comment]
Hi @andresmgot I am facing the same problem with SerializationError: failed to unmarshal error message status code: 404.
It's like

<img width="541" alt="Screen Shot 2022-05-10 at 4 45 28 PM" src="https://user-images.githubusercontent.com/29725020/167592262-fe3f37dc-11b2-460d-a420-b585ad8fdcff.png">

**Comment by andresmgot** [comment]
Thanks @Timyang860629, we should do better to return the error message in the UI. In your case it seems that the error is different. Your image is cropped, does it include more info about the source of the error? (The Grafana logs may help as well to find the root cause).

**Comment by aangelisc** [comment]
Hi @Timyang860629, do you have any more info on the source of that error? Thanks!
