### ISSUE TITLE
Athena Variable Query Editor

### ISSUE THREAD

**Issue by aangelisc** [grafana/athena-datasource#153]
Athena currently only supports a simple query editor which also makes use of the datasources default connection details. The Cloudwatch datasource supports selecting a query type allowing for properties such as `Region`, `Namespace` etc. to be pulled from the backend. A similar editor should be implemented for Athena. The query editor should also be updated to allow for `Region`, `Catalog`, `Database` to be set rather than using default values.

![image](https://user-images.githubusercontent.com/15019026/168095147-ee4eef2d-2698-49b7-bb25-6e6f7a702d45.png)

**Comment by fridgepoet** [comment]
We've decided not to work on this one for now.
