### ISSUE TITLE
Policy error when executing query

### ISSUE THREAD

**Issue by krishna999** [grafana/athena-datasource#156]
**What happened**:
error executing query: AccessDeniedException: User: arn:aws:sts::XXXXX:assumed-role/AmazonGrafanaServiceRole-XXXX/amg-session is not authorized to perform: athena:StartQueryExecution on resource: arn:aws:athena:us-east-1:XXXXXXXX:workgroup/primary because no identity-based policy allows the athena:StartQueryExecution action status code: 400, request id: 0722a7a2-8c8f-4e51-aaec-4b6ae2339a0c

**What you expected to happen**:
When setting up the datasource
**How to reproduce it (as minimally and precisely as possible)**:
Create a datasource and test.

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by fridgepoet** [comment]
Closing because stale, but re-open and let us know if you need something else.
