### ISSUE TITLE
Small typo in the documentation

### ISSUE THREAD

**Issue by CharlesBlonde** [grafana/athena-datasource#158]
**What happened**:

Hi,

First of all, thanks for your work great on this Datasource plugin. I'm starting to using and it's really powerful !

I'm opening this ticket because there is a small typo in the documentation (https://grafana.com/grafana/plugins/grafana-athena-datasource/) :

```
$__rawtimeFrom() => $__rawTimeFrom()
```

I lost a lot of time to understand why it was not working so it can maybe prevent other people to do the same. And I found the solution thanks to this ticket: https://github.com/grafana/athena-datasource/issues/149

**What you expected to happen**:

```
$__rawtimeFrom() => $__rawTimeFrom()
```
in the documentation

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:

Useless information I think

- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by andresmgot** [comment]
thanks for reporting this @CharlesBlonde! maybe you can open a quick PR updating the docs?

**Comment by PrajwalBorkar** [comment]
Please review for any changes :)

**Comment by CharlesBlonde** [comment]
Thanks for the fix and it has been fixed to quickly by @PrajwalBorkar  I wasn't able to do the PR :)

Nevertheless, I didn't realized the typo root source was `README.md`... 

I was personally  using this [page](https://grafana.com/grafana/plugins/grafana-athena-datasource/) as documentation and not the [Github README](https://github.com/grafana/athena-datasource/blob/main/README.md). I guess it will be updated with the next release ?

**Comment by andresmgot** [comment]
> I was personally using this [page](https://grafana.com/grafana/plugins/grafana-athena-datasource/) as documentation and not the [Github README](https://github.com/grafana/athena-datasource/blob/main/README.md). I guess it will be updated with the next release ?

That's correct :+1:
