### ISSUE TITLE
Don't hide Access Key ID in Data Source config

### ISSUE THREAD

**Issue by michael-strigo** [grafana/athena-datasource#178]
Right now, the **Access Key ID** is hidden after the initial configuration was done:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/113865820/194180236-b7eff475-512f-486c-9070-486162a86504.png">

This makes is hard to figure out which credentials set is being used by the connection.

The Access Key ID is **not a secret**. It is being logged in CloudTrail logs to help identify the source of the API request.

Please consider removing this restriction and allow users to see which Access Key they are using.

**Comment by sarahzinger** [comment]
Hi @michael-strigo this is a great suggestion, thanks for filing an issue! We're going to do some research on our end to see if there's any edge case or reasoning that went into hiding these in the first place.

That said even if we make the decision to expose it, just as a heads up it may not be such an easy fix on our end and might take us some time to work on. 

In the meantime, if you need to differentiate from multiple datasources, I might suggest putting the access keys or some other differentiator in the name of the grafana datasource plugin instance. It's a clunky solution, but hopefully helps mitigate the problem somewhat until we can figure out a better solution.
