### ISSUE TITLE
Loading state does not resolve if panel is running a query and editing a panel from the dashboard

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/athena-datasource#182]
If you open up a dashboard and edit a panel that loading, the data doesn't load in the query editor after the query completes.

1. Open the devtools, navigate to network tab
2. Open a dashboard, find a panel that is still loading a query (indicated by the spinning loader icon in the panel header), click the panel header and select "Edit".
3. Wait for the query to finish (see the network tab in devtools to see when `query` finishes)
4. See that the panel header still shows the spinning loader icon and the data does not show up even though the data is available if you inspect the response in the devtools.

`values` has data in the response, but the panel is still showing the loading spinner and no data is shown.
<img width="1387" alt="Screen Shot 2022-11-01 at 4 05 30 PM" src="https://user-images.githubusercontent.com/19530599/199359098-64375436-6d93-42a3-8074-6a646929005c.png">

**Comment by katebrenner** [comment]
We won't prioritize any time soon
