### ISSUE TITLE
Use getDefaultQuery method to set default query

### ISSUE THREAD

**Issue by sunker** [grafana/athena-datasource#186]
Instead of calling onChange to set default query for new queries, we should use the new [getDefaultQuery](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L360) method defined in the data source api. We can use the same default query as today. https://github.com/grafana/athena-datasource/blob/cbc95c28326c2fddf909d1e1208e8cb6e2b98e0a/src/types.ts#L38-L46

Part of https://github.com/grafana/cloud-data-sources/issues/79

**Comment by idastambuk** [comment]
Closing as "won't do"
See https://github.com/grafana/oss-plugin-partnerships/issues/79#issuecomment-1549740717 for info
