### ISSUE TITLE
Java time format doesn't support escape character and uppercase "PM"

### ISSUE THREAD

**Issue by irsath** [grafana/athena-datasource#189]
Hi,

Because of a bug in [viant/toolbox](https://github.com/viant/toolbox/issues/45) one can't have string literal in java datetime format passed to macros.

I created an issue [viant/toolbox/issues/45](https://github.com/viant/toolbox/issues/45).
I'm opening one here as well to keep track of the bug fixe and do the required change on the datasource.

**What happened**:
I used `$__rawTimeFrom("yyyy.MM.dd G 'at' HH:mm:ss z")` and expected a result having the literal `at` in it but the `a` was converted to the literal `pm`.

**How to reproduce it (as minimally and precisely as possible)**:  call a macro that allows a datetimeformat (eg. __rawTimeFrom) with a format that contains a string literal with any pattern letters in it (eg. 'd', 'a', 'y'...)

**Environment**:
- Grafana version: SaaS

**Comment by fridgepoet** [comment]
Hi @irsath thanks for keeping track of that and letting us know!

Just to document for future readers, think this failing test should demonstrate the issue. https://github.com/grafana/athena-datasource/blob/issue-189/pkg/athena/macros_test.go#L122-L132

It looks like the `G` was also not converted according to that documentation you attached on the viant/toolbox https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html#rfc822timezone.

**Comment by fridgepoet** [comment]
By the way, from the Athena documentation, it mentions that it needs to be Joda's [DateTime format](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html). Wouldn't that not include the `at`, for example?

**Comment by irsath** [comment]
So first of all both [Joda's DateTime format](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html) and [Java's DateTime format](https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) define `'` as espace characters for text so it shouldn't matter which implementation is used, both should leave `at` untouched.

Secondly, yes Athena use Joda as you noted but this applies only if you pass any datetime format to Athena. In the case of this issue, the connector don't pass the format to Athena but use it to actually compute the date to pass to Athena.
In other word, doing `SELECT * FROM table WHERE "day" = $__rawTimeFrom("yyyy-MM-dd")` in grafana is actually translated to  `SELECT * FROM table WHERE "day" = '2022-11-29'` by the connector before sending the query to Athena.
So the fact that Athena use Joda or any other implementation has no implication for the issue we face.

 One confusion is that this connector [documentation](https://github.com/grafana/athena-datasource/blob/main/README.md#macros) states that date format must be compliant to Joda's format but the actual implementation of this connector use [viant/toolbox/time_format.go](https://github.com/viant/toolbox/blob/a0456d19ac530af0ba154e0954a13643a5d9432d/time_format.go#L14) which is converting from Java date format to Go date layout.
So the connector document is wrong and should mention Java date format instead of Joda.

**Comment by irsath** [comment]
BTW what I'm saying applies only for `$__rawTimeFrom()` and `$__rawTimeTo()` as those are the two ones that actually don't pass the format to Athena but use the format to compute actual dates in go.

Other macros such as `$__timeFilter(column,format)` indeed pass the format directly to Athena and for such case the format must be compliant with Joda.

**Comment by fridgepoet** [comment]
Thanks, I am wondering a bit (and sorry if this is obvious) why we even involve the Java datetime format in the `rawTimeFrom` macro. How come we can't just use the time formats of Golang for example?

Also another thought is I wonder if there is an alternative to the viant/toolbox library we could use? I didn't find something after a quick search, might've missed something. And in their defense it seems like viant/toolbox has plenty of stars and activity.

**Comment by irsath** [comment]
The only reason I see is to have a consistent interface where all macros accept the same date format (Joda in this case because the underlying datasource ask for Joda).

Having go layout would make sense and actually remove the dependency to viant/toolbox but it would mean having some macro requiring Golang format where others requires Joda format.

**Comment by katebrenner** [comment]
marking as stale
