### ISSUE TITLE
Athena Datasource MVP

### ISSUE THREAD

**Issue by sarahzinger** [grafana/athena-datasource#2]
This epic outlines all the features that need to be implemented for the plugin MVP, according the [Athena Statement of Work](https://docs.google.com/document/d/1V9TGjDTTD3X7EoyGuJlYwWXzf_zNgn2I/edit). 
- [x] https://github.com/grafana/athena-datasource/issues/13
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [ ] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24

**Comment by vickyyyyyyy** [comment]
Closing this - the curated dashboard is no longer part of the MVP/initial release
