### ISSUE TITLE
Add support for Athena result reusing to the datasource plugin

### ISSUE THREAD

**Issue by annerajb** [grafana/athena-datasource#205]
In [november AWS announced athena result reuse (caching)](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-athena-query-result-reuse-accelerate-queries/) on Athena Engine V3 workspaces

This requires passing [two new arguments to the AWS SDK](https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-athena-query-result-reuse-accelerate-queries/) api to start a query execution

The golang version used by this datasource right now is behind the version that supports this argument

[datasource is using v1.44.57](https://github.com/grafana/athena-datasource/blob/main/go.mod#L6)

[This was released on the aws-sdk-go v1.44.150](https://github.com/aws/aws-sdk-go/blame/main/service/athena/api.go#L12782)

Apart from updating the aws-sdk-go go.mod version the query would need to have a new possibly datasource level option (or even better query editor UI menu option) to enable and disable result reuse and configure the amount of seconds to cache the query and obviously submit to the AWS API the new argument on this line of code https://github.com/grafana/athena-datasource/blob/a08e87d6397ae8d8fbc1b13934ff53b92a4ac825/pkg/athena/api/api.go#L59

(is this something you guys accept a PR for?)

**Comment by fridgepoet** [comment]
Hi, thanks for the suggestion! We're looking into it and it sounds great.
You're always welcome to make PRs and we can do our best to incorporate it in whatever solution we come up with. But if not, not to worry, it is on our radar thought we don't have a firm timeline yet.

**Comment by annerajb** [comment]
we started the process for this by merging the upgrade of the aws golang sdk here: 

https://github.com/grafana/athena-datasource/pull/208

once that passes testing no issues are reported i'll continue doing the backend changes for the datasource

**Comment by taleena** [comment]
Hello @annerajb - thank you so much for the interest. We're currently in the process of scoping out adding this feature to the data source. As with many things, there was more to consider beyond the technical aspects. Take a look at the issue @sarahzinger linked above, to see where we're heading with it.

**Comment by fridgepoet** [comment]
Thanks @annerajb for your contribution. We're going ahead with this work in other PRs, so closing this for now. Will let you know when it's ready!
