### ISSUE TITLE
Plugin incompatible with Grafana Cloud since version 2.3.0

### ISSUE THREAD

**Issue by Sadarex** [grafana/athena-datasource#219]
**What happened**:

`Async Query Data Support` was added in version 2.3.0

**What you expected to happen**:

Queries in Grafana Cloud still work.

**How to reproduce it (as minimally and precisely as possible)**:

- Use Grafana Cloud
- Install plugin version 2.3.0 or higher.
- Run Query against Athena

**Response**

```
{
  "request": {
    "method": "POST",
    "url": "api/ds/query",
    "data": {
      "queries": [
        {
          "format": 1,
          "rawSQL": "select *\nfrom tablename\nwhere app = 'name'\nlimit 10",
          "connectionArgs": {
            "region": "__default",
            "catalog": "__default",
            "database": "__default"
          },
          "datasource": {
            "type": "grafana-athena-datasource",
            "uid": "xxx"
          },
          "refId": "A",
          "table": "tablename",
          "meta": {
            "queryFlow": "async"
          },
          "intervalMs": 600000,
          "maxDataPoints": 1037,
          "datasourceId": 9
        }
      ],
      "range": {
        "from": "2023-02-23T13:23:20.165Z",
        "to": "2023-03-02T13:23:20.166Z",
        "raw": {
          "from": "now-7d",
          "to": "now"
        }
      },
      "from": "1677158600165",
      "to": "1677763400166"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "async handler not defined",
        "status": 500,
        "frames": [
          {
            "schema": {
              "name": "A",
              "refId": "A",
              "meta": {
                "executedQueryString": "select *\nfrom tablename\nwhere app = 'name'\nlimit 10"
              },
              "fields": []
            },
            "data": {
              "values": []
            }
          }
        ]
      }
    }
  }
}
```

**Anything else we need to know?**:

Currently only async queries are possible, which requires the feature toggle **athenaAsyncQueryDataSupport**.
Unfortunately feature toggles are not available in Grafana Cloud.

The plugin should have a configuration option to enable/disable the async queries.

**Environment**:
- Grafana version: Grafana Cloud
- Plugin version: 2.6.0

**Comment by iwysiu** [comment]
Hi @Sadarex ! Sorry you're running into issues with the Athena plugin (I'm looking into it). You can ask customer support to disable it in the meantime.

**Comment by iwysiu** [comment]
Hi @Sadarex ! Unfortunately I haven't been able to reproduce this error yet. Can you try to connect with the Athena 2.7.0 version that's just been released? It fixes a different connection related issue and should expose a more helpful error than 2.6.0. Another thing that may help is re-adding the datasource just in case Grafana has gotten into a weird state. Thanks for reporting this issue!

**Comment by fridgepoet** [comment]
Closing a stale issue, feel free to reopen
