### ISSUE TITLE
$__interval_ms seems to crash the plugin?

### ISSUE THREAD

**Issue by mzealey** [grafana/athena-datasource#236]
**What happened**:

`select '$__interval'` correctly returns eg '2s'. `select '$__interval_ms'` hangs for a long time and then sometimes gets an error from the server

**Environment**:
- Grafana version: 9.5.1
- Plugin version: 2.9.2
- OS Grafana is installed on: linux/docker
- User OS & Browser: chrome/linux
- Others:

**Comment by kevinwcyu** [comment]
Thanks for the report @mzealey, just curious when it hangs, does it not have an error? I was able to reproduce it, but it never hangs for me. It always returns an error.

It's coming from https://github.com/grafana/grafana-aws-sdk-react/blob/07bd2a2b9bde2321ad8b85ff40d18544b2bda3c0/src/sql/utils/utils.ts#L29 because `$__interval_ms` is a number instead of a string.

Also for your queries, is there a reason you need to use `$__interval_ms` over `$__interval`?

**Comment by mzealey** [comment]
I couldn't dig into it too much - there was some weird behaviour and it seemed more than just returning an error but it may have been due to something else.I'm not an expert at Athena SQL/grafana macros but I was planning to use an interval as integer to normalize counts over range for graphing, so the obvious way that came to mind was to use the ms interval, but perhaps there is some other way to do this more easily as with some other datasource plugins?On 10 May 2023 19:53, Kevin Yu ***@***.***> wrote:
Thanks for the report @mzealey, just curious when it hangs, does it not have an error? I was able to reproduce it, but it never hangs for me. It always returns an error.
It's coming from https://github.com/grafana/grafana-aws-sdk-react/blob/07bd2a2b9bde2321ad8b85ff40d18544b2bda3c0/src/sql/utils/utils.ts#L29 because $__interval_ms is a number instead of a string.
Also for your queries, is there a reason you need to use $__interval_ms over $__interval?

**Comment by kevinwcyu** [comment]
> I was planning to use an interval as integer to normalize counts over range for graphing, so the obvious way that came to mind was to use the ms interval

Can you provide an example of the query you're trying? I'm not entirely sure what you mean by "use an interval as integer to normalize counts over range".

**Comment by mzealey** [comment]
so for example:

```
select
  $__timeGroup(timestamp, $__interval) AS t
  , count(*) as total
...
group by t
```

will produce a nice graph, but when changing date range because the interval changes with zoom the y-axis numbers change.

So typically (in other sql sources) I would do something like:

```
select
  $__timeGroup(timestamp, $__interval) AS t
  , count(*) / $__interval_ms * 1000 as qps
...
group by t
```

so it's in a scale which does not change with date range level

**Comment by mzealey** [comment]
Thanks very much!
