### ISSUE TITLE
Not a valid zip file

### ISSUE THREAD

**Issue by tp-jssk** [grafana/athena-datasource#248]
**What happened**:
I am getting **Error: X zip: not a valid zip file** at the start up of grafana service.

**What you expected to happen**:
Plugin is installed during the startup of grafana service.

**How to reproduce it (as minimally and precisely as possible)**:
Set following environment variables:
GF_PLUGIN_URL to s3 bucket where plugin zip file is stored
GF_INSTALL_PLUGINS to "grafana-athena-datasource"

**Anything else we need to know?**:
Running Grafana in Airgapped network.

**Environment**:
- Grafana version: 9.5.2
- Plugin version: 2.9.5
- OS Grafana is installed on: Alpine Linux
- User OS & Browser:
- Others: Kubernetes

**Comment by kevinwcyu** [comment]
Hi @tp-jssk, does this work with other data sources or have you only tried with Athena?

**Comment by tp-jssk** [comment]
I've tried only with Athena datasource because in my air-gapped network only athena is available.,

**Comment by tp-jssk** [comment]
I've now, as part of helm chart, added commands to download the file, unzip it in temp folder, then copy it to the /var/lib/grafana/plugins folder. However it DOES NOT show up in the list in Administrator/Plugins page, but it shows up as installed plugin when I run this command: `grafana-cli plugins ls`

**Comment by idastambuk** [comment]
Hi @tp-jssk, just to confirm - the path to "plugins" in your [configuration file](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#linux) is `grafana/plugins`?

**Comment by tp-jssk** [comment]
I found another approach to solve this problem. I ended up grabbing zip file via `initContainers` in K8S, unzipping it to the folder and set the GF_PATHS_PLUGINS env variable. Now `grafana` container picks up the plugin during start up and I can see it via UI.

**Comment by idastambuk** [comment]
Hi @tp-jssk, great to hear you managed to get it working! Just wondering (in order to see if we should make our docs more clear): 
Before you got this working, had you tried installing Athena with `GF_INSTALL_PLUGINS=<url to plugin zip>;<plugin name> `from [this section](https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/#install-plugins-from-other-sources) of the docs? I saw your environment variables, but they're a bit different than this as far as I can see.
Thanks!

**Comment by idastambuk** [comment]
@tp-jssk Can you try separating the plugins with a comma like so: ```GF_INSTALL_PLUGINS=<url1>;<plugin1>,<url2>;<plugin2>```
