### ISSUE TITLE
Minimum query time is 2 seconds

### ISSUE THREAD

**Issue by robbierolin** [grafana/athena-datasource#256]
**What happened**:
We are observing that query times in the Athena plugin take at least 2 seconds to load. We are running with `Query result resuse` enabled and async queries enabled. We can see in the Athena console in AWS that results are cached and the queries take ~200ms to execute, but in Grafana take >2 seconds. I suspect it may have to do with [this line](https://github.com/grafana/grafana-async-query-data-js/blob/main/src/requestLooper.ts#L75). It looks like there is a minimum wait of 2 seconds after the query is submitted before checking on the result. 

I get that the async queries allow us to execute very large queries, but it would also be nice to not sacrifice performance on short queries and take full advantage of the result reuse.

**What you expected to happen**:
Very quick queries, like those using `result reuse` would not have to wait 2 seconds for the result.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a panel with an Athena query in Grafana with athena async queries enabled
2. Enable query result reuse
3. Execute small query
4. Execute again (to trigger result reuse)
5. Observe `/api/ds/query` requests in the network tab >2s apart
6. Observe Athena console in AWS with short runtime <2s

**Environment**:
- Grafana version: v9.4.7 - Amazon Managed Grafana
- Plugin version: 2.8.0
- User OS & Browser: Chrome

**Comment by iwysiu** [comment]
Hi @robbierolin ! Thanks for reporting this issue, I've confirmed it and will add it to our board.

**Comment by kylehounslow** [comment]
Hi team. Any updates on whether this issue will be worked on? AMG customers are reaching out hoping for a fix for their Athena plugin. Thanks

**Comment by jessermejia** [comment]
hi @sarahzinger i noticed that this item has been moved from `Next` to `Backlog`. Are there any plans to prioritize this issue in the near future?

**Comment by sarahzinger** [comment]
Hi @jessermejia, sorry for the confusion, @kevinwcyu is already working on this for the same issue in redshift, the pr is linked.
