### ISSUE TITLE
timeFrom error

### ISSUE THREAD

**Issue by dacevedo12** [grafana/athena-datasource#268]
**What happened**:

I'm using the following query
`SELECT $__timeFrom() AT TIME ZONE 'America/Bogota'`

And get this error
`parsing time "2023-08-01 14:14:33" as "2006-01-02 15:04:05.000": cannot parse "" as ".000": Could not process SQL results`

**What you expected to happen**:

I expected the format returned by timeFrom to be seamlessly compatible with athenea

**Environment**:
- Grafana version: AWS managed grafana v8.4.7
- Plugin version: 2.2.0
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Others: n/a

**Comment by idastambuk** [comment]
Hi @dacevedo12! 
Can you try using $__rawTimeFrom() with the format you need as argument and see if that works? You can find the docs for this [here](__rawTimeFrom). 
Let me know if that works!

**Comment by idastambuk** [comment]
Hi @dacevedo12, have you managed to get this working for you?

**Comment by dacevedo12** [comment]
I solved it like this: `SELECT CAST($__timeFrom() AS timestamp) AT TIME ZONE 'America/Bogota'`
