### ISSUE TITLE
Add a11y linter

### ISSUE THREAD

**Issue by sarahzinger** [grafana/athena-datasource#29]
There's an initiative to add accessibility linters to grafana core that we discussed in frontend weekly. It might be nice to try doing this earlier rather than later to our external plugins: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y

https://github.com/grafana/grafana/issues/37782

**Comment by idastambuk** [comment]
@sarahzinger I assume this is still relevant - can I pick it up?

**Comment by sarahzinger** [comment]
Hi @idastambuk yes totally worth looking into :) I took a look at main grafana and it looks like we're using jsx-a11y now https://github.com/grafana/grafana/blob/45d3125919f0bedb965316685af4723e0bfbb8d9/.eslintrc#L76

I think whenever we update our [eslint config dependency package](https://github.com/grafana/athena-datasource/blob/main/.config/.eslintrc#L7) we'll get that change automatically (if we haven't done so already)? I don't know when that change was added, but it would be awesome to check to see if it's already working in which case we can close this ticket or if it's not there upgrading that package if we can, or if that's not desirable then updating the plugin's eslintrc file here https://github.com/grafana/athena-datasource/blob/main/.eslintrc until we're ready to upgrade.

**Comment by idastambuk** [comment]
> 
It seems like the eslint config package that @grafana/create-plugin pulls from hasn't been updated yet (asked about it in the #frontend channel), so I added it manually [here](https://github.com/grafana/athena-datasource/pull/199) Luckily no errors! 💪🏻🌈
