### ISSUE TITLE
Issue with Athena Datasource Plugin in Amazon Managed Grafana

### ISSUE THREAD

**Issue by yashgangrades** [grafana/athena-datasource#307]
Encountering a 404 Not Found error when trying to instantiate the Athena datasource plugin in Amazon managed Grafana.

I expected the Athena datasource plugin to instantiate without any errors in Amazon managed Grafana.

How to reproduce it:

1. Navigate to the Amazon managed Grafana instance.
2. Download Amazon Athena Plugin latest version
3. Add the Athena Datasource plugin.
4. Attempt to instantiate the plugin, resulting in a 404 Not Found error.

![image](https://github.com/grafana/athena-datasource/assets/148302892/18193fec-b953-487f-9d2a-701ad221d9df)

The issue is specific to Amazon managed Grafana.

**Environment**:
- Grafana version: Grafana v9.4.7
- Plugin version: 2.13.4
- User OS & Browser: Microsoft Edge

**Comment by kevinwcyu** [comment]
Hi @yashgangrades,

Just wanted to check, this only happens after installing the data source the first time? When I install the data source in Amazon Managed Grafana I see the same error, but after I refresh and on subsequent loads, it works.

**Comment by yashgangrades** [comment]
Hi @kevinwcyu 

I'm experiencing the same behavior on my end. The error seems to occur only after the initial installation of the data source in Amazon Managed Grafana. However, like you mentioned, a simple refresh or subsequent loads seem to resolve the problem, and the data source works as expected.

**Comment by kevinwcyu** [comment]
Hi @yashgangrades, I think this may be an issue with Amazon Managed Grafana specifically. It looks like any data source I tried, not just Athena, had this issue as well. I also couldn't recreate it when I was running Grafana v9.4.7 locally, nor do I see it when trying it in Grafana Cloud.

I'd like to close out this issue as this looks like it's specific to Amazon Managed Grafana's handling of installing plugins. You can let the Amazon Managed Grafana team know of this issue.
