### ISSUE TITLE
Query are taking too much time and not giving the output result in grafana

### ISSUE THREAD

**Issue by SricharanSundar** [grafana/athena-datasource#322]
**What happened**:
   We created one Athena query to get the results. In the AWS console the query is executing and giving the result at 7 second. But the grafana is taking too much time and not giving the result in grafana UI.
**What you expected to happen**:
   The grafana need to give a result on time at least it can take 15 seconds but its taking more than 30mins and not giving the result.
**How to reproduce it (as minimally and precisely as possible)**:
   Fix the grafana execution performance.

**Screenshots**

**Anything else we need to know?**:

**Environment**: Build
- Grafana version: 10.4.1
- Plugin version: Latest version from grafana labs
- OS Grafana is installed on: Linux Machine
- User OS & Browser:  Windows(Chrome and explorer)
- Others:

**Comment by iwysiu** [comment]
Hi @SricharanSundar ! I have a few questions about the issue to help us reproduce it. Can you give us an example of the dashboard/query with this issue (If you click the `share` button you can export the dashboard json) or a screen recording? Does this issue happen ever time you run an Athena query or just with specific queries?

**Comment by iwysiu** [comment]
Does your issue seem like it could be related to https://github.com/grafana/athena-datasource/issues/319 ?

**Comment by SricharanSundar** [comment]
> Does your issue seem like it could be related to #319 ?

Comparatively same, But im not getting 504. Taking too much time while giving the result. Is there any other datasource is available to use athena SQL.

**Comment by iwysiu** [comment]
Hi again, @SricharanSundar . This the datasource for connecting with Athena. I have a few questions about the issue to help us reproduce it. Can you give us an example of the dashboard/query with this issue (If you click the `share` button you can export the dashboard json) or can you do a screen recording? Does this issue happen ever time you run an Athena query or just with specific queries?
