### ISSUE TITLE
Adding datasource to Amazon Managed Grafana outputs ec2_iam_role error

### ISSUE THREAD

**Issue by amazonchris** [grafana/athena-datasource#338]
**What happened**: I deploy dashboards programmatically via the Grafana API, my code has not changed.  However, when I create a new 9.4 workspace in Amazon Managed Grafana, install the Athena plugin and attempt to configure it as a Datasource I get the following error:

attempting to use an auth type that is not allowed: "ec2_iam_role": Failed to create client

<img width="1370" alt="Screenshot 2024-06-26 at 9 01 42 AM" src="https://github.com/grafana/athena-datasource/assets/70607347/eff535e2-1559-4be1-bcbd-cc28a3b638df">

<img width="1370" alt="Screenshot 2024-06-26 at 9 05 21 AM" src="https://github.com/grafana/athena-datasource/assets/70607347/be19a131-791d-4eb9-8e0a-1d95f435a9fc">

My SSO user from AWS Identity center also has full permissions to the account and is defined as the Admin user of the workspace.

Note, my Grafana Workspace Role does have full access to Athena.

The call I am making in my lambda is:

```python
                  if plugin == 'athena':
                    body = {'name':self.datasource_name,'type':'grafana-athena-datasource','access':'proxy','url':'','user':'','database':'','basicAuth':False,'isDefault':False,'jsonData':{'authType':'ec2_iam_role','catalog':'AwsDataCatalog','database':self.athena_db,'defaultRegion':self.athena_region,'provisionedBy':'COAST','workgroup':self.athena_workgroup},'readOnly':False}
                  if plugin == 'cloudwatch':
                    body = {'access': 'proxy', 'isDefault': True, 'name': 'Cloudwatch', 'type': plugin}
``` 

**What you expected to happen**:
The datasource provisioned via lambda without issue in the past.

**How to reproduce it (as minimally and precisely as possible)**:
Add Athena Datasource in Grafana, select Workspace IAM role in the drop down and enter ARN of role.

**Environment**:
- Grafana version: 9.4
- Plugin version:2.16.1
- OS Grafana is installed on: Amazon Managed Grafana
- User OS & Browser:
- Others:

**Comment by amazonchris** [comment]
My last known working version I have installed in another workspace is 2.13.6

**Comment by kevinwcyu** [comment]
Hi @amazonchris, I'm releasing v2.16.2 which should fix this. It should be available shortly.
