### ISSUE TITLE
Different results in Grafana Athena Plugin compared to Athena AWS UI: "date" field of Cloudfront logs being coerced to a single date for all logs

### ISSUE THREAD

**Issue by life5ign** [grafana/athena-datasource#345]
**What happened**:
In grafana, the query `select date, time, sc_bytes from cloudfront_standard_logs order by date asc limit 10` yielded
![image](https://github.com/user-attachments/assets/54fc675a-7928-45a5-9466-e933ef911377)

whereas in the athena ui it yielded
![image](https://github.com/user-attachments/assets/a8cec751-93c4-4a50-bdba-e9255d8c3955)

where the athena UI is correct.  It seems all the dates are being changed somehow in transit to grafana?

**What you expected to happen**:
The same results for each.

**How to reproduce it (as minimally and precisely as possible)**:
This is just the cloudfront standard logs setup in an s3 bucket with encryption (not realtime logs), with the queries I illustrated above: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:  10.2.3
- Plugin version: 2.17.1
- OS Grafana is installed on: docker compose on ubuntu linux in ec2
- User OS & Browser: Ubuntu + Brave
- Others:

**Comment by kevinwcyu** [comment]
Hi @life5ign, the date is showing the date in your browser's time. In the Athena console it's rendered as a string. You can get the same formatting with something like this `date_format(date, '%Y-%m-%d') as date`, so your query would be `select date_format(date, '%Y-%m-%d') as date, time, sc_bytes from cloudfront_standard_logs order by date asc limit 10`. This should format it in the same way that the Athena console displays it.

**Comment by life5ign** [comment]
@kevinwcyu thanks for the reply; ok, that makes sense; the date was 7/23 (at midnight), which for me is 7/22 at 17:00.  The query worked great!
