### ISSUE TITLE
Add support for template variables in the connection details selector

### ISSUE THREAD

**Issue by andresmgot** [grafana/athena-datasource#67]
**What happened**:

In case the region / catalog / database are defined in a template variable, it should be possible to select that in the connection details.

Once that is available we can update the current curated dashboard to add support for listing and selecting a database (and not rely just in the default one).

**Screenshots**

![Screenshot from 2021-10-04 16-10-13](https://user-images.githubusercontent.com/4025665/135866480-56ca794c-6797-41d1-87b4-c6f1eb26ea46.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by aangelisc** [comment]
As a part of this would it also be worth imitating the Cloudwatch dashboards VariableEditor and provide the region/catalog/database options?

**Comment by andresmgot** [comment]
hey @aangelisc, as a follow up, can you update the curated dashboards in this plugin so the database selection there is chosen from a template variable rather that the default database?

**Comment by aangelisc** [comment]
> hey @aangelisc, as a follow up, can you update the curated dashboards in this plugin so the database selection there is chosen from a template variable rather that the default database? (like [this](https://github.com/grafana/athena-datasource/blob/main/src/dashboards/cur-monitoring.json#L27))

Yep, I'll get that done @andresmgot 😊
