### ISSUE TITLE
Getting 504 Gateway Timeout after 60 seconds of query runtime

### ISSUE THREAD

**Issue by mourya92** [grafana/athena-datasource#99]
Hello Grafana team, 

I integrated Amazon Managed Grafana dashboard with Athena (both are in same AWS Region including the underlying S3 bucket). With increase in time range, query execution time increases. But, Grafana times out after 1 minute. 

Is there a way to configure this timeout value per data source?

1 minute execution timeout does not satisfy my use-case.

**Comment by sunker** [comment]
Thank you for creating this issue @mourya92. 

Actually, the http client that we use to load athena data doesn't have a timeout specified. The upstream api doesn't have a timeout either, so that mean the timeout is coming from Grafana or AMG. I'm pretty sure we would have seen this timeout already if it was coming from Grafana, so I guess it's coming from AMG. @robbierolin WDYT?

**Comment by robbierolin** [comment]
Amazon Managed Grafana has a timeout of 60 seconds on requests currently. We can evaluate changing it but that may not be the correct path. Isn't the Athena API asynchronous? Is a connection being kept open the entire time?

**Comment by sunker** [comment]
It is asynchronous, but we handle everything (start query, check query status and get query result) in one http request. It’s the same for all sql data sources in Grafana.

**Comment by robbierolin** [comment]
I believe the cloudwatch logs queries are handled asynchronously in multiple requests. These queries can take a long time and it consumes resources to leave connections open. Thoughts on switching Athena and Redshift to use multiple requests?

**Comment by sunker** [comment]
We have no such plans at the moment.

**Comment by sunker** [comment]
I'm gonna close this issue since it's only a problem in AMG. To solve this, timeout needs to be increased in AMG.

**Comment by Yagyansh** [comment]
@sunker I'm getting 504 Timeout issue in Self-hosted Grafana as well after 1 minute. I've tried increasing the dataproxy timeouts to 2 minutes, but still I'm getting the error after 1 minute.

**Comment by andresmgot** [comment]
hi @Yagyansh, maybe you are running Grafana behind another proxy (e.g. Nginx) that is the one timing out the connection?

**Comment by Yagyansh** [comment]
@andresmgot No, I'm not running Grafana behind any proxy. Will increasing the data proxy timeout for Grafana help?

**Comment by andresmgot** [comment]
yes, that should modify the timeout in the Grafana backend. If that doesn't help there, it should be something else timing out. How are you running Grafana?

**Comment by andresmgot** [comment]
You may need to configure the timeout of your Ingress. For example, if it's an Nginx ingress: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-timeouts

**Comment by donnmch** [comment]
I am facing a similar issue with AMG, Athena queries run max for 5/6 seconds but the panels throw the "504 Gateway Time-out" error...after some trial and errors, I observed that the panels thresholds for displaying data can contain around 80k records each, then they timeout.

**Comment by lzmkhan** [comment]
> to be increased in AMG.

I also have the same problem in self hosted grafana.

**Comment by katebrenner** [comment]
@donnmch we will investigate this, and it is being tracked here https://github.com/grafana/athena-datasource/issues/319
